# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: npm install and build webpack
      run: |
        npm install
        npm run build --if-present #comment inline
    - uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: public/
 test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: |
        npm install
        npm test
      env:
        CI: true
#   - name: Archive production artifacts
#      uses: actions/upload-artifact@main
#      with:
#        name: dist-without-markdown
#        path: |
#            dist
#            !dist/**/*.md
#        retention-days: 1
#    - name: Archive code coverage results
#      uses: actions/upload-artifact@v2
#      with:
#         name: code-coverage-report
#         path: output/test/code-coverage.html
